name: Hourly Crypto Pipeline

on:
  schedule:
    # This is "Cron" syntax for "Every hour, at minute 0"
    - cron: '0 * * * *'
  workflow_dispatch: # This allows you to run it manually for testing!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pipeline
        env:
          # This is how you hide your API Keys (Don't hardcode them!)
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py

      - name: Commit and Push DuckDB changes
        run: |
          git config --global user.name "CryptoBot"
          git config --global user.email "bot@github.com"
          git add data/coins.db
          git commit -m "Update crypto data" || exit 0
          git push