name: Crypto Pipeline CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 1. Ingestion test
      - name: Run ingestion script
        run: python ingestion/main.py

      # 2. dbt compile check 
      - name: dbt compile
        run: |
          cd dbt/crypto_pipeline
          dbt compile

      #  3. dbt run + test
      - name: dbt run and test
        run: |
          cd dbt/crypto_pipeline
          dbt run
          dbt test
